name: Integration Test

on:
  workflow_dispatch:

jobs:
  docker_unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Eliona mock
        run: |
          git clone https://github.com/eliona-smart-building-assistant/eliona-mock.git
          cd eliona-mock
          docker-compose up -d

      - name: Wait for Eliona mock to be up
        run: |
          until nc -z localhost 3000; do sleep 1; done

      - name: Install dependencies
        run: go get .
        
      - name: Run integration test
        run: go test -v -run TestApp
        env:
          CONNECTION_STRING: postgres://postgres:secret@172.17.0.1:5432?sslmode=disable
          API_ENDPOINT: http://172.17.0.1:3000/v2
          API_TOKEN: secret
          START_MODE: docker
