name: Integration Test

on:
  workflow_dispatch:

jobs:
  docker_unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Integration Test
        uses: eliona-smart-building-assistant/app-integration-tests@main
        with:
          path: .github/workflows/app_integration_test.yml